[plugin]
repository = "https://github.com/squidmade/WaymarkPresetPlugin.git"
commit = "e798326ec375b442779c836fac7162ca79e03f5d"
owners = [
    "PunishedPineapple",
    "abashby",
]
project_path = "WaymarkPresetPlugin"
changelog = '''
- Update for 6.4
'''
